Avoid a circular import error introduced in Anki 2.1.50
$ python -c "import pytest_anki"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../pytest_anki/__init__.py", line 40, in <module>
    from ._session import AnkiSession  # noqa: F401
  File "/.../pytest_anki/_session.py", line 47, in <module>
    from anki.importing.apkg import AnkiPackageImporter
  File "/.../anki/importing/__init__.py", line 6, in <module>
    from anki import hooks
  File "/.../anki/hooks.py", line 20, in <module>
    from anki.hooks_gen import *
  File "/.../anki/hooks_gen.py", line 14, in <module>
    from anki.cards import Card
  File "/.../anki/cards.py", line 10, in <module>
    import anki.collection
  File "/.../anki/collection.py", line 44, in <module>
    import anki.latex
  File "/.../anki/latex.py", line 15, in <module>
    from anki.models import NotetypeDict
  File "/.../anki/models.py", line 14, in <module>
    import anki.notes
  File "/.../anki/notes.py", line 13, in <module>
    import anki.template
  File "/.../anki/template.py", line 41, in <module>
    from anki.models import NotetypeDict
ImportError: cannot import name 'NotetypeDict' from partially initialized module 'anki.models' (most likely due to a circular import) (/.../anki/models.py)